# syntax=docker/dockerfile:1
FROM python:3.12-slim-bookworm
WORKDIR /tester
ENV DOCKER_TESTING = True
ENV FLIT_ROOT_INSTALL = 1
COPY tests tests
COPY app app
COPY flask_orjson flask_orjson
COPY LICENSE LICENSE
COPY pyproject.toml pyproject.toml
COPY README.md README.md
COPY requirements.txt requirements.txt
COPY requirements_build.txt requirements_build.txt
RUN pip install -r requirements_build.txt
RUN flit install
ENTRYPOINT ["pytest"]
